//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketFinder.svcTicketFinder {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataMicrosTimePeriod", Namespace="http://schemas.datacontract.org/2004/07/Jaxis.POS.Data")]
    [System.SerializableAttribute()]
    public partial class DataMicrosTimePeriod : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimePeriodIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimePeriodNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimePeriodID {
            get {
                return this.TimePeriodIDField;
            }
            set {
                if ((this.TimePeriodIDField.Equals(value) != true)) {
                    this.TimePeriodIDField = value;
                    this.RaisePropertyChanged("TimePeriodID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimePeriodName {
            get {
                return this.TimePeriodNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TimePeriodNameField, value) != true)) {
                    this.TimePeriodNameField = value;
                    this.RaisePropertyChanged("TimePeriodName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataPOSEstablisment", Namespace="http://schemas.datacontract.org/2004/07/Jaxis.POS.Data")]
    [System.SerializableAttribute()]
    public partial class DataPOSEstablisment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstablishmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid EstablishmentIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Establishment {
            get {
                return this.EstablishmentField;
            }
            set {
                if ((object.ReferenceEquals(this.EstablishmentField, value) != true)) {
                    this.EstablishmentField = value;
                    this.RaisePropertyChanged("Establishment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid EstablishmentID {
            get {
                return this.EstablishmentIDField;
            }
            set {
                if ((this.EstablishmentIDField.Equals(value) != true)) {
                    this.EstablishmentIDField = value;
                    this.RaisePropertyChanged("EstablishmentID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatavwPOSTicket", Namespace="http://schemas.datacontract.org/2004/07/Jaxis.POS.Data")]
    [System.SerializableAttribute()]
    public partial class DatavwPOSTicket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CheckNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerTableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DessertCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> DiscountTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EntreeCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstablishmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstablishmentModifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> GuestCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> GuestCountModifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid POSTicketIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PaymentTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PlatCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RawDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RecordTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> TicketDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TicketTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TipAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TouchCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> TransactionTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheckNumber {
            get {
                return this.CheckNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CheckNumberField, value) != true)) {
                    this.CheckNumberField = value;
                    this.RaisePropertyChanged("CheckNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTable {
            get {
                return this.CustomerTableField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerTableField, value) != true)) {
                    this.CustomerTableField = value;
                    this.RaisePropertyChanged("CustomerTable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DessertCount {
            get {
                return this.DessertCountField;
            }
            set {
                if ((this.DessertCountField.Equals(value) != true)) {
                    this.DessertCountField = value;
                    this.RaisePropertyChanged("DessertCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DiscountTotal {
            get {
                return this.DiscountTotalField;
            }
            set {
                if ((this.DiscountTotalField.Equals(value) != true)) {
                    this.DiscountTotalField = value;
                    this.RaisePropertyChanged("DiscountTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EntreeCount {
            get {
                return this.EntreeCountField;
            }
            set {
                if ((this.EntreeCountField.Equals(value) != true)) {
                    this.EntreeCountField = value;
                    this.RaisePropertyChanged("EntreeCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Establishment {
            get {
                return this.EstablishmentField;
            }
            set {
                if ((object.ReferenceEquals(this.EstablishmentField, value) != true)) {
                    this.EstablishmentField = value;
                    this.RaisePropertyChanged("Establishment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstablishmentModified {
            get {
                return this.EstablishmentModifiedField;
            }
            set {
                if ((object.ReferenceEquals(this.EstablishmentModifiedField, value) != true)) {
                    this.EstablishmentModifiedField = value;
                    this.RaisePropertyChanged("EstablishmentModified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> GuestCount {
            get {
                return this.GuestCountField;
            }
            set {
                if ((this.GuestCountField.Equals(value) != true)) {
                    this.GuestCountField = value;
                    this.RaisePropertyChanged("GuestCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> GuestCountModified {
            get {
                return this.GuestCountModifiedField;
            }
            set {
                if ((this.GuestCountModifiedField.Equals(value) != true)) {
                    this.GuestCountModifiedField = value;
                    this.RaisePropertyChanged("GuestCountModified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid POSTicketID {
            get {
                return this.POSTicketIDField;
            }
            set {
                if ((this.POSTicketIDField.Equals(value) != true)) {
                    this.POSTicketIDField = value;
                    this.RaisePropertyChanged("POSTicketID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PaymentTotal {
            get {
                return this.PaymentTotalField;
            }
            set {
                if ((this.PaymentTotalField.Equals(value) != true)) {
                    this.PaymentTotalField = value;
                    this.RaisePropertyChanged("PaymentTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PlatCount {
            get {
                return this.PlatCountField;
            }
            set {
                if ((this.PlatCountField.Equals(value) != true)) {
                    this.PlatCountField = value;
                    this.RaisePropertyChanged("PlatCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RawData {
            get {
                return this.RawDataField;
            }
            set {
                if ((object.ReferenceEquals(this.RawDataField, value) != true)) {
                    this.RawDataField = value;
                    this.RaisePropertyChanged("RawData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RecordType {
            get {
                return this.RecordTypeField;
            }
            set {
                if ((this.RecordTypeField.Equals(value) != true)) {
                    this.RecordTypeField = value;
                    this.RaisePropertyChanged("RecordType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Server {
            get {
                return this.ServerField;
            }
            set {
                if ((object.ReferenceEquals(this.ServerField, value) != true)) {
                    this.ServerField = value;
                    this.RaisePropertyChanged("Server");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServerName {
            get {
                return this.ServerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ServerNameField, value) != true)) {
                    this.ServerNameField = value;
                    this.RaisePropertyChanged("ServerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TicketDate {
            get {
                return this.TicketDateField;
            }
            set {
                if ((this.TicketDateField.Equals(value) != true)) {
                    this.TicketDateField = value;
                    this.RaisePropertyChanged("TicketDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TicketTotal {
            get {
                return this.TicketTotalField;
            }
            set {
                if ((this.TicketTotalField.Equals(value) != true)) {
                    this.TicketTotalField = value;
                    this.RaisePropertyChanged("TicketTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TipAmount {
            get {
                return this.TipAmountField;
            }
            set {
                if ((this.TipAmountField.Equals(value) != true)) {
                    this.TipAmountField = value;
                    this.RaisePropertyChanged("TipAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TouchCount {
            get {
                return this.TouchCountField;
            }
            set {
                if ((this.TouchCountField.Equals(value) != true)) {
                    this.TouchCountField = value;
                    this.RaisePropertyChanged("TouchCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> TransactionType {
            get {
                return this.TransactionTypeField;
            }
            set {
                if ((this.TransactionTypeField.Equals(value) != true)) {
                    this.TransactionTypeField = value;
                    this.RaisePropertyChanged("TransactionType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="POSFile", Namespace="http://schemas.datacontract.org/2004/07/TicketFinderService")]
    [System.SerializableAttribute()]
    public partial class POSFile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DataStreamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ImportTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PathField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] DataStream {
            get {
                return this.DataStreamField;
            }
            set {
                if ((object.ReferenceEquals(this.DataStreamField, value) != true)) {
                    this.DataStreamField = value;
                    this.RaisePropertyChanged("DataStream");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ImportType {
            get {
                return this.ImportTypeField;
            }
            set {
                if ((this.ImportTypeField.Equals(value) != true)) {
                    this.ImportTypeField = value;
                    this.RaisePropertyChanged("ImportType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path {
            get {
                return this.PathField;
            }
            set {
                if ((object.ReferenceEquals(this.PathField, value) != true)) {
                    this.PathField = value;
                    this.RaisePropertyChanged("Path");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="svcTicketFinder.ITicketFinder")]
    public interface ITicketFinder {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicketFinder/GetTimePeriods", ReplyAction="http://tempuri.org/ITicketFinder/GetTimePeriodsResponse")]
        System.Collections.Generic.List<TicketFinder.svcTicketFinder.DataMicrosTimePeriod> GetTimePeriods(System.Guid sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicketFinder/GetTimePeriods", ReplyAction="http://tempuri.org/ITicketFinder/GetTimePeriodsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<TicketFinder.svcTicketFinder.DataMicrosTimePeriod>> GetTimePeriodsAsync(System.Guid sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicketFinder/GetEstablisments", ReplyAction="http://tempuri.org/ITicketFinder/GetEstablismentsResponse")]
        System.Collections.Generic.List<TicketFinder.svcTicketFinder.DataPOSEstablisment> GetEstablisments(System.Guid sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicketFinder/GetEstablisments", ReplyAction="http://tempuri.org/ITicketFinder/GetEstablismentsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<TicketFinder.svcTicketFinder.DataPOSEstablisment>> GetEstablismentsAsync(System.Guid sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicketFinder/GetTicketData", ReplyAction="http://tempuri.org/ITicketFinder/GetTicketDataResponse")]
        System.Collections.Generic.List<TicketFinder.svcTicketFinder.DatavwPOSTicket> GetTicketData(System.Guid sessionID, string ticketNumber, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endTime, string establishment, string ticketText, int timePeriod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicketFinder/GetTicketData", ReplyAction="http://tempuri.org/ITicketFinder/GetTicketDataResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<TicketFinder.svcTicketFinder.DatavwPOSTicket>> GetTicketDataAsync(System.Guid sessionID, string ticketNumber, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endTime, string establishment, string ticketText, int timePeriod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicketFinder/ValidateUser", ReplyAction="http://tempuri.org/ITicketFinder/ValidateUserResponse")]
        string ValidateUser(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicketFinder/ValidateUser", ReplyAction="http://tempuri.org/ITicketFinder/ValidateUserResponse")]
        System.Threading.Tasks.Task<string> ValidateUserAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicketFinder/SubmitFile", ReplyAction="http://tempuri.org/ITicketFinder/SubmitFileResponse")]
        bool SubmitFile(System.Guid customerID, TicketFinder.svcTicketFinder.POSFile file);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicketFinder/SubmitFile", ReplyAction="http://tempuri.org/ITicketFinder/SubmitFileResponse")]
        System.Threading.Tasks.Task<bool> SubmitFileAsync(System.Guid customerID, TicketFinder.svcTicketFinder.POSFile file);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITicketFinderChannel : TicketFinder.svcTicketFinder.ITicketFinder, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TicketFinderClient : System.ServiceModel.ClientBase<TicketFinder.svcTicketFinder.ITicketFinder>, TicketFinder.svcTicketFinder.ITicketFinder {
        
        public TicketFinderClient() {
        }
        
        public TicketFinderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TicketFinderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TicketFinderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TicketFinderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<TicketFinder.svcTicketFinder.DataMicrosTimePeriod> GetTimePeriods(System.Guid sessionID) {
            return base.Channel.GetTimePeriods(sessionID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<TicketFinder.svcTicketFinder.DataMicrosTimePeriod>> GetTimePeriodsAsync(System.Guid sessionID) {
            return base.Channel.GetTimePeriodsAsync(sessionID);
        }
        
        public System.Collections.Generic.List<TicketFinder.svcTicketFinder.DataPOSEstablisment> GetEstablisments(System.Guid sessionID) {
            return base.Channel.GetEstablisments(sessionID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<TicketFinder.svcTicketFinder.DataPOSEstablisment>> GetEstablismentsAsync(System.Guid sessionID) {
            return base.Channel.GetEstablismentsAsync(sessionID);
        }
        
        public System.Collections.Generic.List<TicketFinder.svcTicketFinder.DatavwPOSTicket> GetTicketData(System.Guid sessionID, string ticketNumber, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endTime, string establishment, string ticketText, int timePeriod) {
            return base.Channel.GetTicketData(sessionID, ticketNumber, startDate, endTime, establishment, ticketText, timePeriod);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<TicketFinder.svcTicketFinder.DatavwPOSTicket>> GetTicketDataAsync(System.Guid sessionID, string ticketNumber, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endTime, string establishment, string ticketText, int timePeriod) {
            return base.Channel.GetTicketDataAsync(sessionID, ticketNumber, startDate, endTime, establishment, ticketText, timePeriod);
        }
        
        public string ValidateUser(string userName) {
            return base.Channel.ValidateUser(userName);
        }
        
        public System.Threading.Tasks.Task<string> ValidateUserAsync(string userName) {
            return base.Channel.ValidateUserAsync(userName);
        }
        
        public bool SubmitFile(System.Guid customerID, TicketFinder.svcTicketFinder.POSFile file) {
            return base.Channel.SubmitFile(customerID, file);
        }
        
        public System.Threading.Tasks.Task<bool> SubmitFileAsync(System.Guid customerID, TicketFinder.svcTicketFinder.POSFile file) {
            return base.Channel.SubmitFileAsync(customerID, file);
        }
    }
}
