//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileUpload.svcDataLoaderWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="POSFile", Namespace="http://schemas.datacontract.org/2004/07/Jaxis.Data.Service")]
    [System.SerializableAttribute()]
    public partial class POSFile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DataStreamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ImportTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] DataStream {
            get {
                return this.DataStreamField;
            }
            set {
                if ((object.ReferenceEquals(this.DataStreamField, value) != true)) {
                    this.DataStreamField = value;
                    this.RaisePropertyChanged("DataStream");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ImportType {
            get {
                return this.ImportTypeField;
            }
            set {
                if ((this.ImportTypeField.Equals(value) != true)) {
                    this.ImportTypeField = value;
                    this.RaisePropertyChanged("ImportType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataMicrosTimePeriod", Namespace="http://schemas.datacontract.org/2004/07/Jaxis.POS.Data")]
    [System.SerializableAttribute()]
    public partial class DataMicrosTimePeriod : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimePeriodIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimePeriodNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimePeriodID {
            get {
                return this.TimePeriodIDField;
            }
            set {
                if ((this.TimePeriodIDField.Equals(value) != true)) {
                    this.TimePeriodIDField = value;
                    this.RaisePropertyChanged("TimePeriodID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimePeriodName {
            get {
                return this.TimePeriodNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TimePeriodNameField, value) != true)) {
                    this.TimePeriodNameField = value;
                    this.RaisePropertyChanged("TimePeriodName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataPOSEstablisment", Namespace="http://schemas.datacontract.org/2004/07/Jaxis.POS.Data")]
    [System.SerializableAttribute()]
    public partial class DataPOSEstablisment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstablishmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid EstablishmentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EstablishmentNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Establishment {
            get {
                return this.EstablishmentField;
            }
            set {
                if ((object.ReferenceEquals(this.EstablishmentField, value) != true)) {
                    this.EstablishmentField = value;
                    this.RaisePropertyChanged("Establishment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid EstablishmentID {
            get {
                return this.EstablishmentIDField;
            }
            set {
                if ((this.EstablishmentIDField.Equals(value) != true)) {
                    this.EstablishmentIDField = value;
                    this.RaisePropertyChanged("EstablishmentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EstablishmentNumber {
            get {
                return this.EstablishmentNumberField;
            }
            set {
                if ((this.EstablishmentNumberField.Equals(value) != true)) {
                    this.EstablishmentNumberField = value;
                    this.RaisePropertyChanged("EstablishmentNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatavwPOSTicket", Namespace="http://schemas.datacontract.org/2004/07/Jaxis.POS.Data")]
    [System.SerializableAttribute()]
    public partial class DatavwPOSTicket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BusinessDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CheckNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerTableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DessertCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> DiscountTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EntreeCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstablishmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstablishmentModifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EstablishmentNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> GuestCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> GuestCountModifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid POSTicketIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PaymentTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PlatCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RawDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RecordTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ServerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> TicketDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TicketPeriodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TicketTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TipAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TouchCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TransactionTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BusinessDate {
            get {
                return this.BusinessDateField;
            }
            set {
                if ((this.BusinessDateField.Equals(value) != true)) {
                    this.BusinessDateField = value;
                    this.RaisePropertyChanged("BusinessDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheckNumber {
            get {
                return this.CheckNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CheckNumberField, value) != true)) {
                    this.CheckNumberField = value;
                    this.RaisePropertyChanged("CheckNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTable {
            get {
                return this.CustomerTableField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerTableField, value) != true)) {
                    this.CustomerTableField = value;
                    this.RaisePropertyChanged("CustomerTable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DessertCount {
            get {
                return this.DessertCountField;
            }
            set {
                if ((this.DessertCountField.Equals(value) != true)) {
                    this.DessertCountField = value;
                    this.RaisePropertyChanged("DessertCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DiscountTotal {
            get {
                return this.DiscountTotalField;
            }
            set {
                if ((this.DiscountTotalField.Equals(value) != true)) {
                    this.DiscountTotalField = value;
                    this.RaisePropertyChanged("DiscountTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EntreeCount {
            get {
                return this.EntreeCountField;
            }
            set {
                if ((this.EntreeCountField.Equals(value) != true)) {
                    this.EntreeCountField = value;
                    this.RaisePropertyChanged("EntreeCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Establishment {
            get {
                return this.EstablishmentField;
            }
            set {
                if ((object.ReferenceEquals(this.EstablishmentField, value) != true)) {
                    this.EstablishmentField = value;
                    this.RaisePropertyChanged("Establishment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstablishmentModified {
            get {
                return this.EstablishmentModifiedField;
            }
            set {
                if ((object.ReferenceEquals(this.EstablishmentModifiedField, value) != true)) {
                    this.EstablishmentModifiedField = value;
                    this.RaisePropertyChanged("EstablishmentModified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EstablishmentNumber {
            get {
                return this.EstablishmentNumberField;
            }
            set {
                if ((this.EstablishmentNumberField.Equals(value) != true)) {
                    this.EstablishmentNumberField = value;
                    this.RaisePropertyChanged("EstablishmentNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> GuestCount {
            get {
                return this.GuestCountField;
            }
            set {
                if ((this.GuestCountField.Equals(value) != true)) {
                    this.GuestCountField = value;
                    this.RaisePropertyChanged("GuestCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> GuestCountModified {
            get {
                return this.GuestCountModifiedField;
            }
            set {
                if ((this.GuestCountModifiedField.Equals(value) != true)) {
                    this.GuestCountModifiedField = value;
                    this.RaisePropertyChanged("GuestCountModified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid POSTicketID {
            get {
                return this.POSTicketIDField;
            }
            set {
                if ((this.POSTicketIDField.Equals(value) != true)) {
                    this.POSTicketIDField = value;
                    this.RaisePropertyChanged("POSTicketID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PaymentTotal {
            get {
                return this.PaymentTotalField;
            }
            set {
                if ((this.PaymentTotalField.Equals(value) != true)) {
                    this.PaymentTotalField = value;
                    this.RaisePropertyChanged("PaymentTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PlatCount {
            get {
                return this.PlatCountField;
            }
            set {
                if ((this.PlatCountField.Equals(value) != true)) {
                    this.PlatCountField = value;
                    this.RaisePropertyChanged("PlatCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RawData {
            get {
                return this.RawDataField;
            }
            set {
                if ((object.ReferenceEquals(this.RawDataField, value) != true)) {
                    this.RawDataField = value;
                    this.RaisePropertyChanged("RawData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RecordType {
            get {
                return this.RecordTypeField;
            }
            set {
                if ((this.RecordTypeField.Equals(value) != true)) {
                    this.RecordTypeField = value;
                    this.RaisePropertyChanged("RecordType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Server {
            get {
                return this.ServerField;
            }
            set {
                if ((this.ServerField.Equals(value) != true)) {
                    this.ServerField = value;
                    this.RaisePropertyChanged("Server");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServerName {
            get {
                return this.ServerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ServerNameField, value) != true)) {
                    this.ServerNameField = value;
                    this.RaisePropertyChanged("ServerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TicketDate {
            get {
                return this.TicketDateField;
            }
            set {
                if ((this.TicketDateField.Equals(value) != true)) {
                    this.TicketDateField = value;
                    this.RaisePropertyChanged("TicketDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TicketPeriod {
            get {
                return this.TicketPeriodField;
            }
            set {
                if ((object.ReferenceEquals(this.TicketPeriodField, value) != true)) {
                    this.TicketPeriodField = value;
                    this.RaisePropertyChanged("TicketPeriod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TicketTotal {
            get {
                return this.TicketTotalField;
            }
            set {
                if ((this.TicketTotalField.Equals(value) != true)) {
                    this.TicketTotalField = value;
                    this.RaisePropertyChanged("TicketTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TipAmount {
            get {
                return this.TipAmountField;
            }
            set {
                if ((this.TipAmountField.Equals(value) != true)) {
                    this.TipAmountField = value;
                    this.RaisePropertyChanged("TipAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TouchCount {
            get {
                return this.TouchCountField;
            }
            set {
                if ((this.TouchCountField.Equals(value) != true)) {
                    this.TouchCountField = value;
                    this.RaisePropertyChanged("TouchCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TransactionType {
            get {
                return this.TransactionTypeField;
            }
            set {
                if ((this.TransactionTypeField.Equals(value) != true)) {
                    this.TransactionTypeField = value;
                    this.RaisePropertyChanged("TransactionType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="svcDataLoaderWCF.IDataLoaderWCF")]
    public interface IDataLoaderWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataLoaderWCF/LoadJournalFiles", ReplyAction="http://tempuri.org/IDataLoaderWCF/LoadJournalFilesResponse")]
        bool LoadJournalFiles(System.Guid _customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataLoaderWCF/LoadDataFiles", ReplyAction="http://tempuri.org/IDataLoaderWCF/LoadDataFilesResponse")]
        bool LoadDataFiles(System.Guid _customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataLoaderWCF/SubmitFile", ReplyAction="http://tempuri.org/IDataLoaderWCF/SubmitFileResponse")]
        bool SubmitFile(System.Guid _customerId, FileUpload.svcDataLoaderWCF.POSFile _file);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataLoaderWCF/GetTimePeriods", ReplyAction="http://tempuri.org/IDataLoaderWCF/GetTimePeriodsResponse")]
        System.Collections.Generic.List<FileUpload.svcDataLoaderWCF.DataMicrosTimePeriod> GetTimePeriods(System.Guid _sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataLoaderWCF/GetEstablisments", ReplyAction="http://tempuri.org/IDataLoaderWCF/GetEstablismentsResponse")]
        System.Collections.Generic.List<FileUpload.svcDataLoaderWCF.DataPOSEstablisment> GetEstablisments(System.Guid _sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataLoaderWCF/GetTicketData", ReplyAction="http://tempuri.org/IDataLoaderWCF/GetTicketDataResponse")]
        System.Collections.Generic.List<FileUpload.svcDataLoaderWCF.DatavwPOSTicket> GetTicketData(System.Guid _sessionId, string _ticketNumber, System.Nullable<System.DateTime> _startDate, System.Nullable<System.DateTime> _endTime, string _establishment, string _ticketText, int _timePeriod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataLoaderWCF/Login", ReplyAction="http://tempuri.org/IDataLoaderWCF/LoginResponse")]
        System.Guid Login(string _userId, string _password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataLoaderWCF/GetDataQuery", ReplyAction="http://tempuri.org/IDataLoaderWCF/GetDataQueryResponse")]
        string GetDataQuery(System.Guid _sessionId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataLoaderWCFChannel : FileUpload.svcDataLoaderWCF.IDataLoaderWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataLoaderWCFClient : System.ServiceModel.ClientBase<FileUpload.svcDataLoaderWCF.IDataLoaderWCF>, FileUpload.svcDataLoaderWCF.IDataLoaderWCF {
        
        public DataLoaderWCFClient() {
        }
        
        public DataLoaderWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataLoaderWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataLoaderWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataLoaderWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool LoadJournalFiles(System.Guid _customerId) {
            return base.Channel.LoadJournalFiles(_customerId);
        }
        
        public bool LoadDataFiles(System.Guid _customerId) {
            return base.Channel.LoadDataFiles(_customerId);
        }
        
        public bool SubmitFile(System.Guid _customerId, FileUpload.svcDataLoaderWCF.POSFile _file) {
            return base.Channel.SubmitFile(_customerId, _file);
        }
        
        public System.Collections.Generic.List<FileUpload.svcDataLoaderWCF.DataMicrosTimePeriod> GetTimePeriods(System.Guid _sessionId) {
            return base.Channel.GetTimePeriods(_sessionId);
        }
        
        public System.Collections.Generic.List<FileUpload.svcDataLoaderWCF.DataPOSEstablisment> GetEstablisments(System.Guid _sessionId) {
            return base.Channel.GetEstablisments(_sessionId);
        }
        
        public System.Collections.Generic.List<FileUpload.svcDataLoaderWCF.DatavwPOSTicket> GetTicketData(System.Guid _sessionId, string _ticketNumber, System.Nullable<System.DateTime> _startDate, System.Nullable<System.DateTime> _endTime, string _establishment, string _ticketText, int _timePeriod) {
            return base.Channel.GetTicketData(_sessionId, _ticketNumber, _startDate, _endTime, _establishment, _ticketText, _timePeriod);
        }
        
        public System.Guid Login(string _userId, string _password) {
            return base.Channel.Login(_userId, _password);
        }
        
        public string GetDataQuery(System.Guid _sessionId) {
            return base.Channel.GetDataQuery(_sessionId);
        }
    }
}
